### ISSUE TITLE
Couldn't determine compressed stream type

### ISSUE THREAD

**Issue by NewtonRPG** [TekkaGB/Unverum#8]
![Capture](https://user-images.githubusercontent.com/90364921/132609552-db90ad69-5ddf-4096-9171-b28091450f44.PNG)

**Comment by NewtonRPG** [comment]
Okay, so the only workaround I could do for now was to add the mod directly into the "Mods" folder myself, rather than doing it automatically.

**Comment by TekkaGB** [comment]
This is because due to the ongoing DDoS attacks on GameBanana, the preventative measures are downloading CloudFlare html instead of the actual archives as seen here.  Manual downloads are indeed the workaround for now since the CloudFlare protection doesn't see you as a bot.
![image](https://user-images.githubusercontent.com/70003922/132612600-5ee0b6a6-274c-4562-b64e-fabdc230f865.png)

**Comment by NewtonRPG** [comment]
Ah, thank you for your help!

**Comment by TekkaGB** [comment]
Should be working again

**Comment by NewtonRPG** [comment]
Awesome, thanks!
